# Generated by Django 4.2.7 on 2025-12-11 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_module_details'),
        ('accounts', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, help_text='TOTP secret key (base32 encoded)', max_length=32)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Backup codes for account recovery')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('recovery_email', models.EmailField(blank=True, max_length=254)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
                'db_table': 'two_factor_auth',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'), models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_verified', '2FA Verified'), ('2fa_failed', '2FA Failed'), ('session_created', 'Session Created'), ('session_terminated', 'Session Terminated'), ('ip_blocked', 'IP Blocked'), ('suspicious_activity', 'Suspicious Activity'), ('account_suspended', 'Account Suspended'), ('account_unsuspended', 'Account Unsuspended')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='core.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='security_ev_user_id_70c595_idx'), models.Index(fields=['tenant', 'created_at'], name='security_ev_tenant__b8642d_idx'), models.Index(fields=['event_type', 'created_at'], name='security_ev_event_t_0dd22d_idx'), models.Index(fields=['ip_address', 'created_at'], name='security_ev_ip_addr_b3ff8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length', models.IntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_lowercase', models.BooleanField(default=True)),
                ('require_digits', models.BooleanField(default=True)),
                ('require_special_chars', models.BooleanField(default=True)),
                ('special_chars', models.CharField(default='!@#$%^&*()_+-=[]{}|;:,.<>?', help_text='Allowed special characters', max_length=50)),
                ('password_expiry_days', models.IntegerField(blank=True, help_text='Password expires after N days. Null = no expiration', null=True)),
                ('password_history_count', models.IntegerField(default=5, help_text='Number of previous passwords to remember')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Maximum failed login attempts before lockout')),
                ('lockout_duration_minutes', models.IntegerField(default=30, help_text='Account lockout duration in minutes')),
                ('session_timeout_minutes', models.IntegerField(default=480, help_text='Session timeout in minutes')),
                ('max_concurrent_sessions', models.IntegerField(default=5, help_text='Maximum concurrent sessions per user')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for system-wide policy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_policies', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Password Policies',
                'db_table': 'password_policies',
                'unique_together': {('tenant',)},
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='password_hi_user_id_f4f4ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure: wrong_password, account_locked, 2fa_failed, etc.', max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text="Null if username doesn't exist", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['username', 'attempted_at'], name='login_attem_usernam_74b89f_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='login_attem_ip_addr_bdf4e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('ip_range', models.CharField(blank=True, help_text='CIDR notation: 192.168.1.0/24', max_length=50)),
                ('is_whitelist', models.BooleanField(default=True, help_text='True for whitelist, False for blacklist')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_rules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelists', to='core.tenant')),
            ],
            options={
                'verbose_name': 'IP Whitelist/Blacklist',
                'verbose_name_plural': 'IP Whitelists/Blacklists',
                'db_table': 'ip_whitelists',
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='ip_whitelis_tenant__9f3013_idx'), models.Index(fields=['ip_address'], name='ip_whitelis_ip_addr_0e7d52_idx')],
                'unique_together': {('tenant', 'ip_address')},
            },
        ),
    ]
