# Generated by Django 5.2 on 2025-12-12 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_security_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number in E.164 format', max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_verification_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code', 'is_used'], name='sms_verific_user_id_1593a8_idx'), models.Index(fields=['phone_number', 'code', 'is_used'], name='sms_verific_phone_n_8461f1_idx')],
            },
        ),
    ]
