# Generated by Django 4.2.7 on 2026-01-06 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_smsverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_accepted', models.BooleanField(default=False, help_text='User accepted Terms and Conditions')),
                ('privacy_accepted', models.BooleanField(default=False, help_text='User accepted Privacy Policy')),
                ('terms_version', models.CharField(blank=True, help_text='Version of Terms and Conditions that was accepted', max_length=50)),
                ('privacy_version', models.CharField(blank=True, help_text='Version of Privacy Policy that was accepted', max_length=50)),
                ('terms_accepted_at', models.DateTimeField(blank=True, help_text='When Terms were accepted', null=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, help_text='When Privacy Policy was accepted', null=True)),
                ('first_accepted_at', models.DateTimeField(auto_now_add=True, help_text='First time user accepted any agreement')),
                ('last_updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('accepted_from_ip', models.GenericIPAddressField(blank=True, help_text='IP address when agreements were accepted', null=True)),
                ('user', models.OneToOneField(help_text='User who accepted the agreements', on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Agreement',
                'verbose_name_plural': 'User Agreements',
                'db_table': 'user_agreements',
            },
        ),
        migrations.DeleteModel(
            name='SMSVerificationCode',
        ),
    ]
