# Generated by Django 4.2.7 on 2026-01-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useragreement_delete_smsverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Device/browser fingerprint to track acceptance per device', max_length=255),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User agent string when agreements were accepted'),
        ),
    ]
