# Generated by Django 4.2.7 on 2026-01-06 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useragreement_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragreement',
            name='user',
            field=models.ForeignKey(help_text='User who accepted the agreements', on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL),
        ),
    ]
