# Generated by Django 5.2 on 2025-12-12 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_add_module_details'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('purchase', 'After Purchase'), ('abandoned_cart', 'Abandoned Cart'), ('birthday', 'Customer Birthday'), ('anniversary', 'Account Anniversary'), ('low_stock', 'Low Stock Alert'), ('new_product', 'New Product Added'), ('price_drop', 'Price Drop'), ('back_in_stock', 'Back in Stock'), ('cart_reminder', 'Cart Reminder'), ('welcome', 'Welcome Series'), ('win_back', 'Win-Back Campaign')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='Additional trigger conditions')),
                ('workflow_steps', models.JSONField(default=list, help_text="Array of workflow steps, e.g., [{'action': 'send_email', 'template_id': 1, 'delay': 0}, ...]")),
                ('total_triggered', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_workflows', to='core.tenant')),
            ],
            options={
                'db_table': 'automation_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField(help_text='HTML template with variables like {{customer_name}}, {{product_name}}, etc.')),
                ('plain_text_content', models.TextField(blank=True, help_text='Plain text version')),
                ('category', models.CharField(choices=[('transactional', 'Transactional'), ('promotional', 'Promotional'), ('newsletter', 'Newsletter'), ('notification', 'Notification'), ('custom', 'Custom')], default='promotional', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for system-wide templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='core.tenant')),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('email', 'Email Campaign'), ('sms', 'SMS Campaign'), ('push', 'Push Notification'), ('combined', 'Combined Campaign')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_segment', models.CharField(choices=[('all', 'All Customers'), ('segment', 'Customer Segment'), ('custom', 'Custom Filter')], default='all', max_length=50)),
                ('customer_segment_id', models.IntegerField(blank=True, null=True)),
                ('custom_filter', models.JSONField(blank=True, default=dict, help_text='Custom filter criteria')),
                ('subject', models.CharField(blank=True, help_text='Email subject or SMS preview', max_length=255)),
                ('message_template', models.TextField(help_text='Message template with variables')),
                ('html_content', models.TextField(blank=True, help_text='HTML content for emails')),
                ('is_automated', models.BooleanField(default=False, help_text='Is this an automated campaign?')),
                ('automation_trigger', models.CharField(blank=True, choices=[('purchase', 'After Purchase'), ('abandoned_cart', 'Abandoned Cart'), ('birthday', 'Birthday'), ('anniversary', 'Account Anniversary'), ('low_stock', 'Low Stock Alert'), ('new_product', 'New Product'), ('sale', 'Sale/Promotion'), ('custom', 'Custom Trigger')], max_length=50)),
                ('max_recipients', models.IntegerField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('bounce_count', models.IntegerField(default=0)),
                ('unsubscribe_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='core.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='core.tenant')),
            ],
            options={
                'db_table': 'marketing_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('converted', 'Converted'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='customers.customer')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.marketingcampaign')),
            ],
            options={
                'db_table': 'campaign_recipients',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, help_text='URL to open when notification is clicked')),
                ('image_url', models.URLField(blank=True)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('customer', 'Specific Customer'), ('segment', 'Customer Segment')], default='all', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='core.tenant')),
            ],
            options={
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform_account_id', models.CharField(blank=True, max_length=255)),
                ('platform_username', models.CharField(blank=True, max_length=255)),
                ('platform_data', models.JSONField(blank=True, default=dict)),
                ('auto_post_new_products', models.BooleanField(default=False)),
                ('auto_post_promotions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_integrations', to='core.tenant')),
            ],
            options={
                'db_table': 'social_media_integrations',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('current_step', models.IntegerField(default=0)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('execution_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='customers.customer')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='marketing.automationworkflow')),
            ],
            options={
                'db_table': 'automation_executions',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['workflow', 'status'], name='automation__workflo_b727fa_idx'), models.Index(fields=['customer', 'status'], name='automation__custome_681087_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['tenant', 'status'], name='marketing_c_tenant__5d46ea_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['campaign_type', 'status'], name='marketing_c_campaig_17a2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['scheduled_at'], name='marketing_c_schedul_278c75_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='campaign_re_campaig_6c3c85_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['customer'], name='campaign_re_custome_566a2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaintegration',
            unique_together={('tenant', 'platform')},
        ),
    ]
