# Generated by Django 4.2.7 on 2025-12-10 00:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_add_pricing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='core.tenant')),
            ],
            options={
                'db_table': 'expense_categories',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('tax_period_start', models.DateField(blank=True, null=True)),
                ('tax_period_end', models.DateField(blank=True, null=True)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT (Value Added Tax)'), ('income_tax', 'Income Tax'), ('paye', 'PAYE (Pay As You Earn)'), ('aids_levy', 'AIDS Levy'), ('nssa', 'NSSA Contributions'), ('zimdef', 'ZIMDEF Levy'), ('customs', 'Customs Duty'), ('excise', 'Excise Duty'), ('withholding', 'Withholding Tax'), ('other', 'Other Tax')], default='vat', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('tax_authority', models.CharField(default='ZIMRA', help_text='Tax authority name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='core.tenant')),
            ],
            options={
                'db_table': 'tax_transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='tax_transac_tenant__dcde58_idx'), models.Index(fields=['tenant', 'tax_type'], name='tax_transac_tenant__0493ea_idx'), models.Index(fields=['tax_number'], name='tax_transac_tax_num_8852ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('expense_type', models.CharField(choices=[('operating', 'Operating Expenses'), ('shipping', 'Shipping/Delivery Costs'), ('warehouse', 'Warehouse/Storage Costs'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('salaries', 'Salaries & Wages'), ('marketing', 'Marketing & Advertising'), ('insurance', 'Insurance'), ('maintenance', 'Maintenance & Repairs'), ('office', 'Office Supplies'), ('professional', 'Professional Fees'), ('taxes', 'Taxes (Other)'), ('depreciation', 'Depreciation'), ('other', 'Other Expenses')], default='operating', max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('ecocash', 'EcoCash'), ('other', 'Other')], default='cash', max_length=50)),
                ('paid', models.BooleanField(default=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_supplier', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.expensecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.tenant')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='expenses_tenant__298db5_idx'), models.Index(fields=['tenant', 'expense_type'], name='expenses_tenant__b6991a_idx'), models.Index(fields=['expense_number'], name='expenses_expense_003f04_idx')],
            },
        ),
    ]
