# Generated by Django 4.2.7 on 2026-01-01 10:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_notifications'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('vat', 'VAT'), ('income_tax', 'Income Tax'), ('paye', 'PAYE')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(help_text="e.g., 'January 2024', 'Q1 2024'", max_length=100)),
                ('filing_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('filed', 'Filed'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='not_started', max_length=20)),
                ('filing_due_date', models.DateField()),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('tax_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax amount due', max_digits=10)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid', max_digits=10)),
                ('return_reference', models.CharField(blank=True, help_text='ZIMRA return reference number', max_length=100)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_periods', to='core.tenant')),
            ],
            options={
                'db_table': 'tax_periods',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='TaxLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('vat_output', 'VAT Output (Sales)'), ('vat_input', 'VAT Input (Purchases)'), ('income_tax', 'Income Tax'), ('paye', 'PAYE'), ('aids_levy', 'AIDS Levy'), ('nssa', 'NSSA'), ('zimdef', 'ZIMDEF'), ('other', 'Other')], max_length=50)),
                ('source_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('payroll', 'Payroll'), ('manual', 'Manual Entry')], max_length=50)),
                ('source_id', models.IntegerField(help_text='ID of the source transaction')),
                ('taxable_amount', models.DecimalField(decimal_places=2, help_text='Amount subject to tax (before tax)', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage applied', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Tax amount accrued', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_period_start', models.DateField(help_text='Start of tax period this liability belongs to')),
                ('tax_period_end', models.DateField(help_text='End of tax period')),
                ('is_settled', models.BooleanField(default=False, help_text='Whether tax has been paid/filed')),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('tax_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to='accounting.taxperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_liabilities', to='core.tenant')),
            ],
            options={
                'db_table': 'tax_liabilities',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_number', models.CharField(blank=True, help_text='ZIMRA VAT registration number', max_length=50)),
                ('vat_registration_date', models.DateField(blank=True, null=True)),
                ('standard_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('14.50'), help_text='Standard VAT rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('vat_filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('income_tax_filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='annually', max_length=20)),
                ('tax_year_start_month', models.IntegerField(default=1, help_text='Month when tax year starts (1=January)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('income_tax_brackets', models.JSONField(default=list, help_text="Income tax brackets: [{'min': 0, 'max': 300000, 'rate': 0}, ...]")),
                ('paye_enabled', models.BooleanField(default=True)),
                ('paye_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PAYE threshold amount per month', max_digits=10)),
                ('aids_levy_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='AIDS Levy rate percentage (on taxable income)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('nssa_enabled', models.BooleanField(default=True)),
                ('nssa_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='NSSA employee contribution rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('nssa_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('4.50'), help_text='NSSA employer contribution rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('zimdef_enabled', models.BooleanField(default=True)),
                ('zimdef_rate', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='ZIMDEF levy rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('auto_calculate_tax', models.BooleanField(default=True, help_text='Automatically calculate tax on sales and purchases')),
                ('tax_inclusive_pricing', models.BooleanField(default=False, help_text='Prices include tax (tax-inclusive) or exclude tax (tax-exclusive)')),
                ('zimra_api_key', models.CharField(blank=True, help_text='ZIMRA API key for direct filing', max_length=255)),
                ('zimra_api_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configuration', to='core.tenant')),
            ],
            options={
                'db_table': 'tax_configurations',
            },
        ),
        migrations.AddIndex(
            model_name='taxperiod',
            index=models.Index(fields=['tenant', 'period_type', 'period_end'], name='tax_periods_tenant__a63ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='taxperiod',
            index=models.Index(fields=['filing_status', 'filing_due_date'], name='tax_periods_filing__aa10ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxperiod',
            unique_together={('tenant', 'period_type', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='taxliability',
            index=models.Index(fields=['tenant', 'tax_type', 'is_settled'], name='tax_liabili_tenant__a0f309_idx'),
        ),
        migrations.AddIndex(
            model_name='taxliability',
            index=models.Index(fields=['tenant', 'tax_period_start', 'tax_period_end'], name='tax_liabili_tenant__87f5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='taxliability',
            index=models.Index(fields=['source_type', 'source_id'], name='tax_liabili_source__99ed4e_idx'),
        ),
    ]
