# Generated by Django 4.2.7 on 2026-01-02 10:52

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_taxperiod_taxliability_taxconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Account code (e.g., 1000, 2000)', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('account_type', models.CharField(choices=[('asset_current', 'Current Asset'), ('asset_fixed', 'Fixed Asset'), ('asset_intangible', 'Intangible Asset'), ('liability_current', 'Current Liability'), ('liability_long_term', 'Long-Term Liability'), ('equity', 'Equity'), ('equity_retained', 'Retained Earnings'), ('revenue', 'Revenue'), ('revenue_other', 'Other Income'), ('expense', 'Expense'), ('expense_cogs', 'Cost of Goods Sold')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_account', models.BooleanField(default=False, help_text='System-generated accounts cannot be deleted')),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('allow_manual_entries', models.BooleanField(default=True, help_text='Allow manual journal entries to this account')),
                ('requires_reconciliation', models.BooleanField(default=False, help_text='This account requires periodic reconciliation (e.g., bank accounts)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='accounting.chartofaccounts')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_accounts', to='core.tenant')),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, help_text='External reference (invoice, receipt, etc.)', max_length=255)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual Entry'), ('sale', 'Sale Transaction'), ('purchase', 'Purchase Transaction'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('expense', 'Expense'), ('adjustment', 'Adjustment'), ('closing', 'Closing Entry'), ('opening', 'Opening Balance')], default='manual', max_length=50)),
                ('is_posted', models.BooleanField(db_index=True, default=False, help_text='Posted entries are locked and cannot be edited')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, help_text='Entry that reverses this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.tenant')),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (must be 0.00 if credit_amount > 0)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (must be 0.00 if debit_amount > 0)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccounts')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'journal_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('opening_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opening_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounting.chartofaccounts')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger', to='core.tenant')),
            ],
            options={
                'db_table': 'general_ledger',
                'ordering': ['account', 'period_year', 'period_month'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'date'], name='journal_ent_tenant__505b56_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'is_posted'], name='journal_ent_tenant__c67940_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'entry_type'], name='journal_ent_tenant__55c550_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_number'], name='journal_ent_entry_n_60b5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['tenant', 'period_year', 'period_month'], name='general_led_tenant__8ccbea_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['account', 'period_year', 'period_month'], name='general_led_account_7e9316_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generalledger',
            unique_together={('tenant', 'account', 'period_year', 'period_month')},
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['tenant', 'account_type'], name='chart_of_ac_tenant__7ece12_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['tenant', 'is_active'], name='chart_of_ac_tenant__0f9970_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccounts',
            unique_together={('tenant', 'code')},
        ),
    ]
