# Generated by Django 4.2.7 on 2025-12-06 13:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsplit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='aids_levy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='USD', help_text='Primary transaction currency', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='device_code',
            field=models.CharField(blank=True, help_text='Fiscal device code', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='fiscal_number',
            field=models.CharField(blank=True, help_text='Fiscal invoice number', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_offline',
            field=models.BooleanField(default=False, help_text='Sale processed offline'),
        ),
        migrations.AddField(
            model_name='sale',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='When offline sale was synced', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentsplit',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('card', 'Card (Swipe)'), ('zipit', 'ZIPIT'), ('usd', 'USD Cash'), ('zwl', 'ZWL Cash'), ('zar', 'ZAR Cash'), ('rtgs', 'RTGS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentsplit',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction reference/EcoCash number', max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('telecash', 'Telecash'), ('card', 'Card (Swipe)'), ('zipit', 'ZIPIT'), ('usd', 'USD Cash'), ('zwl', 'ZWL Cash'), ('zar', 'ZAR Cash'), ('rtgs', 'RTGS'), ('credit', 'Credit'), ('split', 'Split Payment')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('voided', 'Voided'), ('returned', 'Returned'), ('suspended', 'Suspended')], default='completed', max_length=20),
        ),
    ]
