# Generated by Django 4.2.7 on 2025-12-06 13:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_till_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_add_zim_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('float_zwl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('float_zar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shift_date', models.DateField()),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('opening_cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('opening_cash_zwl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('closing_cash_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closing_cash_zwl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reconciled', 'Reconciled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_floats', to='core.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='till_floats', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_floats', to='core.tenant')),
            ],
            options={
                'db_table': 'till_floats',
                'ordering': ['-shift_date', '-shift_start'],
                'unique_together': {('branch', 'cashier', 'shift_date', 'status')},
            },
        ),
        migrations.CreateModel(
            name='SuspendedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField(help_text='Serialized cart items')),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='suspended', max_length=20)),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('sale_id', models.IntegerField(blank=True, help_text='Sale ID when resumed', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspended_sales', to='core.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspended_sales', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspended_sales', to='core.tenant')),
            ],
            options={
                'db_table': 'suspended_sales',
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.CreateModel(
            name='DayEndReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('x_report', 'X-Report'), ('z_report', 'Z-Report')], max_length=20)),
                ('total_sales_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_sales_zwl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_sales_zar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_zwl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ecocash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('onemoney', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('card', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('zipit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rtgs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expected_cash_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_cash_zwl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cash_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cash_zwl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_zwl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report_data', models.JSONField(help_text='Complete report data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_end_reports', to='core.branch')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_end_reports', to='core.tenant')),
                ('till_float', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_end_reports', to='pos.tillfloat')),
            ],
            options={
                'db_table': 'day_end_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('float_in', 'Float In'), ('float_out', 'Float Out'), ('safe_drop', 'Safe Drop'), ('expense', 'Expense'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='core.tenant')),
                ('till_float', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='pos.tillfloat')),
            ],
            options={
                'db_table': 'cash_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
