# Generated by Django 4.2.7 on 2025-12-06 13:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_rfid_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_add_till_models'),
        ('customers', '0001_initial'),
        ('pos', '0003_add_till_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Promo code', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('amount', 'Fixed Amount Discount'), ('bogo', 'Buy One Get One Free'), ('bogf', 'Buy X Get Y Free'), ('happy_hour', 'Happy Hour'), ('seasonal', 'Seasonal Sale')], default='percentage', max_length=50)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('buy_quantity', models.IntegerField(default=1, help_text='Buy X items')),
                ('get_quantity', models.IntegerField(default=1, help_text='Get Y items free')),
                ('apply_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Category'), ('product', 'Specific Product'), ('customer', 'Specific Customer'), ('min_purchase', 'Minimum Purchase Amount')], default='all', max_length=20)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, help_text='Happy hour start', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Happy hour end', null=True)),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated: 0=Monday, 6=Sunday', max_length=20)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of uses', null=True)),
                ('max_uses_per_customer', models.IntegerField(blank=True, help_text='Max uses per customer', null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Require supervisor approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.tenant')),
            ],
            options={
                'db_table': 'promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='pos.promotion')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.sale')),
            ],
            options={
                'db_table': 'promotion_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('override_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_override_approvals', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_override_requests', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='pos.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='core.tenant')),
            ],
            options={
                'db_table': 'price_overrides',
                'ordering': ['-created_at'],
            },
        ),
    ]
