# Generated by Django 4.2.7 on 2025-12-07 17:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('inventory', '0003_add_industry_specific_models'),
        ('core', '0009_add_pricing_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
        ('pos', '0004_add_promotion_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(choices=[('defective', 'Defective/Damaged Goods'), ('wrong_item', 'Wrong Item Received'), ('overstocked', 'Overstocked'), ('expired', 'Expired Products'), ('quality_issue', 'Quality Issue'), ('customer_return', 'Customer Returned to Us'), ('other', 'Other')], default='other', max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('received_by_supplier', 'Received by Supplier'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('supplier_acknowledged', models.BooleanField(default=False)),
                ('supplier_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_credit_note', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Supervisor who approved the return', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='core.branch')),
                ('created_by', models.ForeignKey(help_text='User who created the return', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='core.tenant')),
            ],
            options={
                'db_table': 'purchase_returns',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(choices=[('defective', 'Defective/Damaged Product'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('duplicate', 'Duplicate Purchase'), ('expired', 'Expired Product'), ('other', 'Other')], default='other', max_length=50)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details about the return')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash Refund'), ('ecocash', 'EcoCash Refund'), ('card', 'Card Refund'), ('store_credit', 'Store Credit'), ('exchange', 'Exchange Only'), ('no_refund', 'No Refund')], default='cash', max_length=50)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Supervisor who approved the return', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='core.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='customers.customer')),
                ('processed_by', models.ForeignKey(help_text='Cashier who processed the return', on_delete=django.db.models.deletion.PROTECT, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_returns', to='core.tenant')),
            ],
            options={
                'db_table': 'sale_returns',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New/Unopened'), ('opened', 'Opened'), ('damaged', 'Damaged'), ('defective', 'Defective')], default='new', max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='pos.saleitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salereturn')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant')),
            ],
            options={
                'db_table': 'sale_return_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New/Unopened'), ('opened', 'Opened'), ('damaged', 'Damaged'), ('defective', 'Defective'), ('expired', 'Expired')], default='new', max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseorderitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.purchasereturn')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant')),
            ],
            options={
                'db_table': 'purchase_return_items',
            },
        ),
    ]
