# Generated by Django 4.2.7 on 2025-12-07 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantmodule',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='activated_by',
            field=models.ForeignKey(blank=True, help_text='User/admin who activated this module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about activation (e.g., payment confirmation)'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When module activation was requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='requires_owner_approval',
            field=models.BooleanField(default=False, help_text='Whether owner approval is required for activation'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('requires_payment', 'Requires Payment'), ('trial', 'Trial Access'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', help_text='Activation status of this module', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='enabled_at',
            field=models.DateTimeField(blank=True, help_text='When module was activated', null=True),
        ),
    ]
