# Generated by Django 4.2.7 on 2025-12-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_module_activation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmodule',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When module was activated', null=True),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='activation_period_months',
            field=models.IntegerField(default=1, help_text='Activation period in months (1 for monthly, 12 for yearly)'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price paid for the activation period', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency for pricing', max_length=3),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When module activation expires', null=True),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='payment_type',
            field=models.CharField(choices=[('trial', 'Trial'), ('paid', 'Paid'), ('debt', 'Debt'), ('complimentary', 'Complimentary')], default='trial', help_text='How this module is being paid for', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price at time of activation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price at time of activation', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='enabled_at',
            field=models.DateTimeField(blank=True, help_text='When module was activated (legacy)', null=True),
        ),
    ]
