# Generated by Django 4.2.7 on 2026-01-01 11:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_add_notifications'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('segment_type', models.CharField(choices=[('rfm', 'RFM Analysis'), ('behavioral', 'Behavioral'), ('demographic', 'Demographic'), ('value', 'Value-Based'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('rfm_recency_min', models.IntegerField(blank=True, help_text='Minimum recency score (1-5)', null=True)),
                ('rfm_recency_max', models.IntegerField(blank=True, help_text='Maximum recency score (1-5)', null=True)),
                ('rfm_frequency_min', models.IntegerField(blank=True, help_text='Minimum frequency score (1-5)', null=True)),
                ('rfm_frequency_max', models.IntegerField(blank=True, help_text='Maximum frequency score (1-5)', null=True)),
                ('rfm_monetary_min', models.IntegerField(blank=True, help_text='Minimum monetary score (1-5)', null=True)),
                ('rfm_monetary_max', models.IntegerField(blank=True, help_text='Maximum monetary score (1-5)', null=True)),
                ('behavioral_criteria', models.JSONField(blank=True, default=dict, help_text='Behavioral segmentation rules')),
                ('auto_assign', models.BooleanField(default=False, help_text='Automatically assign customers to this segment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segments', to='core.tenant')),
            ],
            options={
                'db_table': 'customer_segments',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tier name (Bronze, Silver, Gold, Platinum)', max_length=50)),
                ('level', models.IntegerField(help_text='Tier level (1=lowest, higher=better)')),
                ('min_points', models.IntegerField(default=0, help_text='Minimum points required for this tier')),
                ('min_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum spend required', max_digits=10)),
                ('min_purchases', models.IntegerField(default=0, help_text='Minimum number of purchases required')),
                ('benefits', models.JSONField(blank=True, default=dict, help_text="Tier benefits (e.g., {'points_multiplier': 1.5, 'discount_percentage': 10})")),
                ('points_earn_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points earned per currency unit (e.g., 1.5 = 1.5 points per $1)', max_digits=5)),
                ('points_expiry_days', models.IntegerField(blank=True, help_text='Days before points expire (null = no expiry)', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='core.tenant')),
            ],
            options={
                'db_table': 'loyalty_tiers',
                'ordering': ['level'],
                'unique_together': {('tenant', 'level')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points_cost', models.IntegerField(help_text='Points required to redeem', validators=[django.core.validators.MinValueValidator(1)])),
                ('monetary_value', models.DecimalField(blank=True, decimal_places=2, help_text='Equivalent monetary value', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Available quantity (null = unlimited)', null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('redemption_count', models.IntegerField(default=0, help_text='Number of times redeemed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='core.tenant')),
                ('tier_required', models.ForeignKey(blank=True, help_text='Minimum tier required to redeem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='customers.loyaltytier')),
            ],
            options={
                'db_table': 'loyalty_rewards',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_redemptions', to='customers.customer')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='customers.loyaltyreward')),
            ],
            options={
                'db_table': 'loyalty_redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_tier_change', models.DateTimeField(auto_now=True)),
                ('points_earned_lifetime', models.IntegerField(default=0, help_text='Total points earned (lifetime)')),
                ('points_used_lifetime', models.IntegerField(default=0, help_text='Total points used (lifetime)')),
                ('points_balance', models.IntegerField(default=0, help_text='Current points balance')),
                ('current_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current period spend', max_digits=10)),
                ('current_purchases', models.IntegerField(default=0, help_text='Current period purchase count')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tier_membership', to='customers.customer')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='customers.loyaltytier')),
            ],
            options={
                'db_table': 'customer_loyalty_tiers',
            },
        ),
        migrations.CreateModel(
            name='CustomerTouchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchpoint_type', models.CharField(choices=[('sale', 'Sale'), ('purchase_return', 'Purchase Return'), ('email', 'Email'), ('sms', 'SMS'), ('phone_call', 'Phone Call'), ('visit', 'Store Visit'), ('website_visit', 'Website Visit'), ('campaign_response', 'Campaign Response'), ('support_ticket', 'Support Ticket'), ('review', 'Review'), ('social_media', 'Social Media'), ('other', 'Other')], max_length=30)),
                ('channel', models.CharField(choices=[('in_store', 'In Store'), ('online', 'Online'), ('phone', 'Phone'), ('email', 'Email'), ('sms', 'SMS'), ('social_media', 'Social Media'), ('mobile_app', 'Mobile App'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (Sale, Email, etc.)', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='ID of referenced object', max_length=255)),
                ('outcome', models.CharField(blank=True, help_text='Outcome (purchase, inquiry, complaint, etc.)', max_length=50)),
                ('outcome_value', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value of outcome', max_digits=10, null=True)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_touchpoints', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='User who interacted', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_touchpoints',
                'ordering': ['-interaction_date'],
                'indexes': [models.Index(fields=['customer', '-interaction_date'], name='customer_to_custome_4cb2dd_idx'), models.Index(fields=['tenant', 'touchpoint_type', '-interaction_date'], name='customer_to_tenant__a1a21c_idx'), models.Index(fields=['reference_type', 'reference_id'], name='customer_to_referen_3581ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to='customers.customer')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='customers.customersegment')),
            ],
            options={
                'db_table': 'customer_segment_memberships',
                'ordering': ['-assigned_at'],
                'unique_together': {('customer', 'segment')},
            },
        ),
        migrations.CreateModel(
            name='CustomerRFMScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_score', models.IntegerField(help_text='Recency score (1=oldest, 5=newest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('frequency_score', models.IntegerField(help_text='Frequency score (1=lowest, 5=highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('monetary_score', models.IntegerField(help_text='Monetary score (1=lowest, 5=highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recency_days', models.IntegerField(help_text='Days since last purchase')),
                ('frequency_count', models.IntegerField(help_text='Number of purchases in analysis period')),
                ('monetary_value', models.DecimalField(decimal_places=2, help_text='Total monetary value in analysis period', max_digits=10)),
                ('rfm_score', models.CharField(help_text="Combined RFM score (e.g., '555', '432')", max_length=10)),
                ('analysis_period_start', models.DateField()),
                ('analysis_period_end', models.DateField()),
                ('suggested_segment', models.CharField(blank=True, help_text='Suggested segment based on RFM', max_length=100)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_score', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rfm_scores', to='core.tenant')),
            ],
            options={
                'db_table': 'customer_rfm_scores',
                'indexes': [models.Index(fields=['tenant', 'rfm_score'], name='customer_rf_tenant__fe66b5_idx'), models.Index(fields=['customer', '-calculated_at'], name='customer_rf_custome_1a087a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerLifetimeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_clv', models.DecimalField(decimal_places=2, help_text='Historical lifetime value (actual revenue)', max_digits=10)),
                ('predictive_clv', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted future lifetime value', max_digits=10, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, help_text='Total revenue from customer', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of serving customer', max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, help_text='Total profit from customer', max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, help_text='Average order value', max_digits=10)),
                ('purchase_frequency', models.DecimalField(decimal_places=2, help_text='Purchases per period', max_digits=5)),
                ('customer_age_days', models.IntegerField(help_text='Customer age in days')),
                ('calculation_date', models.DateField(default=django.utils.timezone.now)),
                ('period_start', models.DateField(help_text='Start date for calculation period')),
                ('period_end', models.DateField(help_text='End date for calculation period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clv_records', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_clv_records', to='core.tenant')),
            ],
            options={
                'db_table': 'customer_lifetime_values',
                'ordering': ['-calculation_date'],
                'indexes': [models.Index(fields=['tenant', '-historical_clv'], name='customer_li_tenant__70dd6e_idx'), models.Index(fields=['customer', '-calculation_date'], name='customer_li_custome_550692_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerJourneyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('awareness', 'Awareness'), ('consideration', 'Consideration'), ('purchase', 'Purchase'), ('post_purchase', 'Post-Purchase'), ('loyalty', 'Loyalty'), ('advocacy', 'Advocacy'), ('churned', 'Churned')], max_length=20)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.IntegerField(default=0, help_text='Engagement score at this stage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('converted', models.BooleanField(default=False, help_text='Did customer convert at this stage?')),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_stages', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_journey_stages', to='core.tenant')),
            ],
            options={
                'db_table': 'customer_journey_stages',
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['customer', '-entered_at'], name='customer_jo_custome_ed964a_idx'), models.Index(fields=['tenant', 'stage', '-entered_at'], name='customer_jo_tenant__83a3ae_idx')],
            },
        ),
    ]
