# Generated by Django 4.2.7 on 2025-12-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rfid_tag',
            field=models.CharField(blank=True, db_index=True, help_text='RFID tag identifier', max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'rfid_tag'], name='products_tenant__bf4e5d_idx'),
        ),
    ]
