# Generated by Django 4.2.7 on 2025-12-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_industry_specific_models'),
        ('inventory', '0002_add_rfid_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', models.TextField(blank=True, default='{}', help_text='Category-specific field values stored as JSON string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_fields', to='core.tenant')),
            ],
            options={
                'db_table': 'product_custom_fields',
                'indexes': [models.Index(fields=['tenant', 'product'], name='product_cus_tenant__3a2a28_idx')],
            },
        ),
    ]
