# Generated by Django 4.2.7 on 2025-12-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_industry_specific_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('sale', 'Sale'), ('return', 'Return'), ('return_restored', 'Return Restored to Inventory'), ('return_disposed', 'Return Disposed (Damaged)'), ('return_to_supplier', 'Return to Supplier'), ('purchase_return_disposed', 'Purchase Return Disposed (Cannot Return)')], max_length=30),
        ),
    ]
