# Generated by Django 4.2.7 on 2026-01-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_notifications'),
        ('inventory', '0005_cyclecount_picklist_putaway_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Short code like 'A', 'B', 'FREEZER'", max_length=20)),
                ('description', models.TextField(blank=True)),
                ('zone_type', models.CharField(choices=[('standard', 'Standard'), ('refrigerated', 'Refrigerated'), ('frozen', 'Frozen'), ('hazardous', 'Hazardous'), ('bulk', 'Bulk Storage'), ('quarantine', 'Quarantine')], default='standard', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_zones', to='core.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_zones', to='core.tenant')),
            ],
            options={
                'db_table': 'warehouse_zones',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'branch', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SerialNumberPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pattern name', max_length=100)),
                ('pattern_type', models.CharField(choices=[('regex', 'Regular Expression'), ('prefix_suffix', 'Prefix + Suffix with Range'), ('sequential', 'Sequential Numbers'), ('alphanumeric', 'Alphanumeric Pattern')], default='prefix_suffix', max_length=50)),
                ('pattern_config', models.JSONField(default=dict, help_text='Pattern configuration (prefix, suffix, range, regex, etc.)')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Specific product, or null for all products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial_patterns', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_patterns', to='core.tenant')),
            ],
            options={
                'db_table': 'serial_number_patterns',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(help_text="Full location code like 'A-3-2-5' or 'AISLE-3-SHELF-2-BIN-5'", max_length=100)),
                ('aisle', models.CharField(blank=True, help_text='Aisle number or identifier', max_length=50)),
                ('shelf', models.CharField(blank=True, help_text='Shelf number or level', max_length=50)),
                ('bin', models.CharField(blank=True, help_text='Bin or slot number', max_length=50)),
                ('row', models.CharField(blank=True, help_text='Row number', max_length=50)),
                ('level', models.CharField(blank=True, help_text='Level/floor', max_length=50)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity this location can hold', max_digits=10, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Dimensions: {length, width, height, unit}')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_locations', to='core.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_locations', to='core.tenant')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='inventory.warehousezone')),
            ],
            options={
                'db_table': 'product_locations',
                'ordering': ['zone', 'location_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductLocationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Current quantity at this location', max_digits=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/default location for this product')),
                ('last_stocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_picked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='inventory.productlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_mappings', to='inventory.product')),
            ],
            options={
                'db_table': 'product_location_mappings',
                'indexes': [models.Index(fields=['product', 'is_primary'], name='product_loc_product_01e296_idx'), models.Index(fields=['location', 'quantity'], name='product_loc_locatio_e3676c_idx')],
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.AddIndex(
            model_name='productlocation',
            index=models.Index(fields=['tenant', 'branch', 'location_code'], name='product_loc_tenant__4331e5_idx'),
        ),
        migrations.AddIndex(
            model_name='productlocation',
            index=models.Index(fields=['zone', 'location_code'], name='product_loc_zone_id_14c603_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productlocation',
            unique_together={('tenant', 'branch', 'location_code')},
        ),
    ]
