"""
Management command to enhance modules with detailed descriptions, features, and benefits.
"""
from django.core.management.base import BaseCommand
from core.models import Module


class Command(BaseCommand):
    help = 'Enhance existing modules with detailed descriptions, features, and benefits'
    
    def handle(self, *args, **options):
        self.stdout.write('Enhancing modules with detailed information...')
        
        # Comprehensive module enhancements
        module_enhancements = {
            'inventory': {
                'detailed_description': 'Complete inventory control system with real-time stock tracking, automated alerts, batch management, and multi-location support. Optimize your stock levels and reduce wastage with intelligent inventory insights.',
                'features': [
                    'Real-time stock tracking across all locations',
                    'Automated low stock and expiry alerts',
                    'Batch and serial number tracking',
                    'Barcode scanning support',
                    'Multi-warehouse management',
                    'Stock movement history and audit trail',
                    'ABC analysis and inventory valuation',
                    'Supplier integration for reorder points',
                ],
                'benefits': [
                    'Reduce stockouts by 60% with automated alerts',
                    'Minimize waste with expiry tracking',
                    'Save 10+ hours weekly on inventory counts',
                    'Improve cash flow with optimized stock levels',
                    'Ensure compliance with batch tracking',
                ],
                'use_cases': [
                    'Track thousands of products across multiple branches',
                    'Manage expiry dates for perishable goods',
                    'Monitor slow-moving items and optimize orders',
                    'Maintain accurate stock levels for online and offline sales',
                ],
                'target_business_types': ['grocery', 'pharmacy', 'electronics', 'general_retail', 'wholesale'],
                'icon': '📦',
                'highlight_color': '#667eea',
                'is_featured': True,
            },
            'pos': {
                'detailed_description': 'Modern point-of-sale system designed for speed and efficiency. Process sales quickly, accept multiple payment methods, print receipts, and manage transactions seamlessly. Works online and offline.',
                'features': [
                    'Lightning-fast checkout with barcode scanning',
                    'Multiple payment methods (cash, card, mobile money)',
                    'Offline mode for internet interruptions',
                    'Receipt printing and email receipts',
                    'Suspend and resume sales',
                    'Split payments and partial payments',
                    'Discounts and promotions management',
                    'Customer quick search at checkout',
                ],
                'benefits': [
                    'Process transactions 3x faster than manual systems',
                    'Reduce cashier errors by 90%',
                    'Accept all payment methods in one system',
                    'Continue selling even without internet',
                    'Provide instant receipts to customers',
                ],
                'use_cases': [
                    'Fast checkout during peak hours',
                    'Handle multiple payment methods in one transaction',
                    'Process sales offline during network issues',
                    'Manage promotions and discounts at point of sale',
                ],
                'target_business_types': ['all'],
                'icon': '💳',
                'highlight_color': '#27ae60',
                'is_featured': True,
            },
            'sales_customers': {
                'detailed_description': 'Build lasting customer relationships with comprehensive CRM features. Track purchase history, manage loyalty programs, send targeted promotions, and understand your customers better.',
                'features': [
                    'Complete customer database with purchase history',
                    'Loyalty points and rewards system',
                    'Customer segmentation and tagging',
                    'Purchase history and analytics',
                    'Credit management for customer accounts',
                    'Marketing campaigns and promotions',
                    'Customer communication tools',
                    'VIP customer identification',
                ],
                'benefits': [
                    'Increase repeat purchases by 40%',
                    'Boost average transaction value with upsells',
                    'Build customer loyalty with rewards programs',
                    'Target promotions effectively with segmentation',
                    'Improve customer retention',
                ],
                'use_cases': [
                    'Reward loyal customers with points',
                    'Send birthday promotions automatically',
                    'Identify top customers for VIP treatment',
                    'Manage customer credit accounts',
                ],
                'target_business_types': ['clothing', 'electronics', 'jewellery', 'furniture', 'general_retail'],
                'icon': '👥',
                'highlight_color': '#3498db',
                'is_featured': False,
            },
            'suppliers_purchases': {
                'detailed_description': 'Streamline your purchasing process from supplier selection to goods received. Manage purchase orders, track deliveries, compare supplier prices, and maintain supplier relationships.',
                'features': [
                    'Supplier database with contact information',
                    'Purchase order creation and tracking',
                    'Goods Received Notes (GRN) management',
                    'Supplier price comparison',
                    'Purchase history and analytics',
                    'Supplier performance tracking',
                    'Reorder suggestions based on stock levels',
                    'Payment tracking for suppliers',
                ],
                'benefits': [
                    'Save 5+ hours weekly on purchase management',
                    'Reduce overstocking with smart reorder points',
                    'Negotiate better prices with supplier comparison',
                    'Ensure timely deliveries with order tracking',
                    'Maintain better supplier relationships',
                ],
                'use_cases': [
                    'Create and track purchase orders',
                    'Compare prices from multiple suppliers',
                    'Manage goods received and quality checks',
                    'Track supplier performance and payments',
                ],
                'target_business_types': ['wholesale', 'grocery', 'electronics', 'general_retail'],
                'icon': '🛒',
                'highlight_color': '#e67e22',
                'is_featured': False,
            },
            'roles_permissions': {
                'detailed_description': 'Control access and permissions with granular role-based access control. Assign roles to staff, control what they can see and do, and maintain security across your business.',
                'features': [
                    'Predefined roles (Admin, Manager, Cashier, etc.)',
                    'Custom role creation with fine-grained permissions',
                    'Module-level access control',
                    'Action-level permissions (view, create, edit, delete)',
                    'Branch-specific access control',
                    'Audit trail of user actions',
                    'Time-based access restrictions',
                    'Multi-factor authentication support',
                ],
                'benefits': [
                    'Protect sensitive business data',
                    'Prevent unauthorized actions',
                    'Comply with security requirements',
                    'Monitor staff activities with audit trails',
                    'Scale security as business grows',
                ],
                'use_cases': [
                    'Restrict cashier access to refunds',
                    'Give managers view-only access to reports',
                    'Limit branch managers to their branch only',
                    'Track who made changes to critical data',
                ],
                'target_business_types': ['all'],
                'icon': '🔒',
                'highlight_color': '#e74c3c',
                'is_featured': False,
            },
            'financial_reporting': {
                'detailed_description': 'Get complete financial insights with comprehensive reporting. Track sales, expenses, profits, taxes, and generate professional reports for stakeholders and tax compliance.',
                'features': [
                    'Real-time sales and revenue reports',
                    'Profit & Loss statements',
                    'Balance sheets and financial summaries',
                    'Tax reporting and compliance',
                    'Expense tracking and categorization',
                    'Cash flow analysis',
                    'Comparative period analysis',
                    'Export to PDF and Excel',
                ],
                'benefits': [
                    'Make data-driven business decisions',
                    'Simplify tax filing with automated reports',
                    'Identify profitable products and categories',
                    'Monitor cash flow in real-time',
                    'Present professional reports to stakeholders',
                ],
                'use_cases': [
                    'Generate monthly P&L statements',
                    'Track expenses by category',
                    'Monitor sales trends over time',
                    'Prepare financial reports for tax filing',
                ],
                'target_business_types': ['all'],
                'icon': '📊',
                'highlight_color': '#9b59b6',
                'is_featured': True,
            },
            'ai_analytics': {
                'detailed_description': 'Leverage artificial intelligence for smart business insights. Get sales predictions, inventory recommendations, customer behavior analysis, and automated alerts.',
                'features': [
                    'AI-powered sales forecasting',
                    'Demand prediction for inventory',
                    'Customer behavior analysis',
                    'Anomaly detection for unusual patterns',
                    'Automated business recommendations',
                    'Trend analysis and predictions',
                    'Smart alerts for opportunities',
                    'Predictive analytics dashboard',
                ],
                'benefits': [
                    'Increase revenue by 15-25% with AI insights',
                    'Reduce dead stock with demand prediction',
                    'Identify growth opportunities automatically',
                    'Make informed decisions with predictions',
                    'Stay ahead of market trends',
                ],
                'use_cases': [
                    'Predict which products will sell well',
                    'Identify customers likely to churn',
                    'Detect unusual sales patterns',
                    'Get recommendations for promotions',
                ],
                'target_business_types': ['electronics', 'clothing', 'general_retail', 'wholesale'],
                'icon': '🤖',
                'highlight_color': '#16a085',
                'is_featured': True,
            },
            'multi_branch': {
                'detailed_description': 'Manage multiple locations seamlessly. Centralized control with branch-level autonomy. Transfer stock, compare performance, and manage all branches from one dashboard.',
                'features': [
                    'Unlimited branch management',
                    'Inter-branch stock transfers',
                    'Branch performance comparison',
                    'Centralized inventory visibility',
                    'Branch-specific pricing and promotions',
                    'Cross-branch sales reporting',
                    'Branch manager autonomy',
                    'Unified customer database',
                ],
                'benefits': [
                    'Scale business to multiple locations easily',
                    'Optimize stock across all branches',
                    'Compare branch performance',
                    'Maintain consistency across locations',
                    'Reduce overhead with centralized management',
                ],
                'use_cases': [
                    'Manage stock across 5+ locations',
                    'Transfer slow-moving items between branches',
                    'Compare sales performance by branch',
                    'Set branch-specific promotions',
                ],
                'target_business_types': ['general_retail', 'clothing', 'electronics', 'wholesale', 'restaurant'],
                'icon': '🏢',
                'highlight_color': '#2980b9',
                'is_featured': True,
            },
            'ecommerce_integration': {
                'detailed_description': 'Sell online and in-store with unified inventory. Sync products, orders, and customers between your physical store and online shop automatically.',
                'features': [
                    'Real-time inventory sync between online and offline',
                    'Unified order management',
                    'Online order fulfillment tracking',
                    'E-commerce platform integrations',
                    'Unified customer accounts',
                    'Online payment processing',
                    'Shipping management',
                    'Marketplace integration (Amazon, eBay, etc.)',
                ],
                'benefits': [
                    'Double sales by reaching online customers',
                    'Eliminate overselling with real-time sync',
                    'Manage online and offline from one system',
                    'Provide seamless customer experience',
                    'Expand to new markets easily',
                ],
                'use_cases': [
                    'Sell on website and in physical store',
                    'Fulfill online orders from store inventory',
                    'Sync product catalog automatically',
                    'Manage marketplace listings',
                ],
                'target_business_types': ['electronics', 'clothing', 'furniture', 'jewellery', 'general_retail'],
                'icon': '🌐',
                'highlight_color': '#f39c12',
                'is_featured': True,
            },
            'mobile_app': {
                'detailed_description': 'Manage your business on the go with our mobile manager app. View dashboards, approve transactions, check inventory, and make decisions from anywhere.',
                'features': [
                    'Real-time dashboard on mobile',
                    'Approve transactions remotely',
                    'Inventory checking and updates',
                    'Sales monitoring',
                    'Push notifications for important events',
                    'Mobile reporting',
                    'Photo capture for receipts and products',
                    'Offline capability',
                ],
                'benefits': [
                    'Manage business from anywhere',
                    'Respond to issues immediately',
                    'Stay informed with push notifications',
                    'Make decisions on the go',
                    'Save time with mobile approvals',
                ],
                'use_cases': [
                    'Approve large discounts while away',
                    'Check inventory while visiting suppliers',
                    'Monitor sales during peak hours',
                    'Receive alerts for low stock',
                ],
                'target_business_types': ['all'],
                'icon': '📱',
                'highlight_color': '#1abc9c',
                'is_featured': False,
            },
            'accounting': {
                'detailed_description': 'Full double-entry bookkeeping system with chart of accounts, journal entries, general ledger, trial balance, balance sheet, and cash flow statements. Complete accounting solution for small to medium businesses.',
                'features': [
                    'Chart of Accounts with hierarchical structure',
                    'Journal Entries with debit/credit balancing',
                    'General Ledger with period-based tracking',
                    'Trial Balance reports',
                    'Balance Sheet generation',
                    'Cash Flow Statements',
                    'Account aging reports (A/R and A/P)',
                    'Financial statement generation',
                    'Integration with sales and purchases',
                    'Tax compliance support',
                ],
                'benefits': [
                    'Complete accounting solution in one system',
                    'Generate professional financial statements',
                    'Ensure accurate double-entry bookkeeping',
                    'Simplify tax preparation and filing',
                    'Track financial performance in real-time',
                    'Maintain GAAP-compliant records',
                ],
                'use_cases': [
                    'Generate monthly financial statements',
                    'Track all financial transactions',
                    'Prepare for audits and tax filing',
                    'Monitor business financial health',
                    'Manage accounts payable and receivable',
                ],
                'target_business_types': ['all'],
                'icon': '📊',
                'highlight_color': '#3498db',
                'is_featured': True,
            },
            'quotations_invoicing': {
                'detailed_description': 'Professional quotations and invoicing system with company branding. Create, send, and track quotations. Convert accepted quotations to invoices. Manage invoice payments and track outstanding balances. Perfect for consulting firms, professional services, and B2B businesses.',
                'features': [
                    'Create professional quotations with line items',
                    'Auto-generate quotation and invoice numbers',
                    'Convert quotations to invoices with one click',
                    'Company branding on all documents (logo, signatures)',
                    'Multiple line items with descriptions and pricing',
                    'Tax calculation and discount support',
                    'Payment tracking for invoices',
                    'Overdue invoice alerts',
                    'Terms and conditions management',
                    'PDF generation for quotations and invoices',
                    'Email quotations and invoices to customers',
                    'Payment history tracking',
                ],
                'benefits': [
                    'Present professional quotations to win more business',
                    'Streamline quotation-to-invoice workflow',
                    'Track all outstanding invoices and payments',
                    'Reduce time spent on document creation by 80%',
                    'Improve cash flow with payment tracking',
                    'Maintain consistent branding across all documents',
                ],
                'use_cases': [
                    'Send quotations to potential clients',
                    'Convert accepted quotations to invoices automatically',
                    'Track invoice payments and outstanding balances',
                    'Generate branded PDF documents for clients',
                    'Manage recurring service invoices',
                    'Monitor overdue invoices and follow up',
                ],
                'target_business_types': ['professional_services', 'services', 'wholesale', 'corporate'],
                'icon': '📄',
                'highlight_color': '#9b59b6',
                'is_featured': True,
            },
            'accounting_integration': {
                'detailed_description': 'Seamlessly integrate with popular accounting software. Automate bookkeeping, sync transactions, and eliminate manual data entry.',
                'features': [
                    'Integration with QuickBooks, Xero, Sage',
                    'Automatic transaction sync',
                    'Chart of accounts mapping',
                    'Invoice and payment sync',
                    'Expense categorization',
                    'Bank reconciliation support',
                    'Tax code mapping',
                    'Real-time sync or scheduled sync',
                ],
                'benefits': [
                    'Save 10+ hours monthly on bookkeeping',
                    'Eliminate manual data entry errors',
                    'Maintain accurate books automatically',
                    'Simplify tax preparation',
                    'Get financial insights faster',
                ],
                'use_cases': [
                    'Sync sales to accounting software automatically',
                    'Reconcile bank accounts easily',
                    'Generate accounting reports',
                    'Prepare for tax filing',
                ],
                'target_business_types': ['all'],
                'icon': '📚',
                'highlight_color': '#34495e',
                'is_featured': False,
            },
            'barcode_automation': {
                'detailed_description': 'Automate inventory and sales with barcode and QR code scanning. Speed up checkout, reduce errors, and streamline inventory management.',
                'features': [
                    'Barcode scanning at POS',
                    'Barcode generation for products',
                    'QR code support',
                    'Batch barcode printing',
                    'Mobile scanner support',
                    'Barcode validation',
                    'Integration with barcode printers',
                    'Custom barcode formats',
                ],
                'benefits': [
                    'Speed up checkout by 50%',
                    'Reduce pricing errors to zero',
                    'Fast inventory counting',
                    'Professional product labeling',
                    'Improve customer experience',
                ],
                'use_cases': [
                    'Scan products at checkout',
                    'Generate barcodes for new products',
                    'Conduct fast inventory counts',
                    'Print shelf labels',
                ],
                'target_business_types': ['grocery', 'electronics', 'general_retail', 'wholesale'],
                'icon': '📷',
                'highlight_color': '#8e44ad',
                'is_featured': False,
            },
            'offline_pos': {
                'detailed_description': 'Never lose a sale with full offline POS capability. Process transactions, print receipts, and manage inventory even without internet connection.',
                'features': [
                    'Complete POS functionality offline',
                    'Automatic sync when connection restored',
                    'Offline receipt printing',
                    'Local data storage',
                    'Conflict resolution on sync',
                    'Offline inventory checks',
                    'Offline customer lookup',
                    'Data integrity checks',
                ],
                'benefits': [
                    'Never lose sales due to internet issues',
                    'Continue operations during outages',
                    'Maintain customer service standards',
                    'Ensure data consistency',
                    'Work from remote locations',
                ],
                'use_cases': [
                    'Process sales during internet outage',
                    'Work at events without internet',
                    'Serve customers in areas with poor connectivity',
                    'Maintain operations during network maintenance',
                ],
                'target_business_types': ['all'],
                'icon': '📡',
                'highlight_color': '#27ae60',
                'is_featured': True,
            },
            'security_features': {
                'detailed_description': 'Advanced security features to protect your business data. Monitor access, detect fraud, and maintain compliance with industry standards.',
                'features': [
                    'Advanced user authentication',
                    'Fraud detection and alerts',
                    'Transaction monitoring',
                    'IP whitelisting',
                    'Session management',
                    'Data encryption at rest and in transit',
                    'Regular security audits',
                    'Compliance reporting (PCI DSS, GDPR)',
                ],
                'benefits': [
                    'Protect against fraud and theft',
                    'Comply with security regulations',
                    'Maintain customer trust',
                    'Monitor suspicious activities',
                    'Secure sensitive business data',
                ],
                'use_cases': [
                    'Detect unusual transaction patterns',
                    'Monitor staff access to sensitive data',
                    'Ensure compliance with regulations',
                    'Protect against data breaches',
                ],
                'target_business_types': ['all'],
                'icon': '🛡️',
                'highlight_color': '#c0392b',
                'is_featured': False,
            },
            'grocery_module': {
                'detailed_description': 'Specialized features for grocery stores and supermarkets. Manage expiry dates, weight-based pricing, bulk items, and perishable goods efficiently.',
                'features': [
                    'Expiry date tracking and alerts',
                    'Weight-based pricing (per kg/lb)',
                    'Bulk item management',
                    'Unit conversion (kg to pieces)',
                    'Fresh produce management',
                    'Promotions on bulk purchases',
                    'Supplier lot tracking',
                    'Waste tracking and reporting',
                ],
                'benefits': [
                    'Reduce food waste by 40%',
                    'Prevent expired products sales',
                    'Handle weight-based items easily',
                    'Optimize fresh produce inventory',
                    'Comply with food safety regulations',
                ],
                'use_cases': [
                    'Track expiry dates for dairy products',
                    'Price fruits and vegetables by weight',
                    'Manage bulk rice and grains',
                    'Monitor perishable goods stock',
                ],
                'target_business_types': ['grocery'],
                'icon': '🛒',
                'highlight_color': '#27ae60',
                'is_featured': False,
            },
            'electronics_module': {
                'detailed_description': 'Specialized features for electronics retailers. Track serial numbers, manage warranties, handle repairs, and manage technical specifications.',
                'features': [
                    'Serial number tracking',
                    'Warranty management',
                    'Repair tracking',
                    'Technical specifications storage',
                    'IMEI tracking for phones',
                    'Accessory management',
                    'Compatibility checking',
                    'Warranty claim processing',
                ],
                'benefits': [
                    'Track high-value items individually',
                    'Manage warranties efficiently',
                    'Prevent duplicate serial number sales',
                    'Handle repairs professionally',
                    'Improve customer service',
                ],
                'use_cases': [
                    'Track serial numbers for warranty',
                    'Process warranty claims',
                    'Manage phone and tablet repairs',
                    'Track accessories with main products',
                ],
                'target_business_types': ['electronics', 'motor_spares'],
                'icon': '📱',
                'highlight_color': '#3498db',
                'is_featured': False,
            },
            'boutique_module': {
                'detailed_description': 'Fashion retail specialized features. Manage sizes, colors, variants, style codes, seasonal collections, and fashion trends.',
                'features': [
                    'Size and color variant management',
                    'Style code tracking',
                    'Seasonal collection management',
                    'Size chart management',
                    'Fashion trend tracking',
                    'Visual product catalog',
                    'Lookbook creation',
                    'Style recommendations',
                ],
                'benefits': [
                    'Manage fashion inventory efficiently',
                    'Track sizes and colors accurately',
                    'Plan seasonal collections',
                    'Improve visual merchandising',
                    'Reduce size-related returns',
                ],
                'use_cases': [
                    'Manage clothing by size and color',
                    'Track seasonal fashion collections',
                    'Create lookbooks for customers',
                    'Manage style variations',
                ],
                'target_business_types': ['clothing', 'cosmetics'],
                'icon': '👗',
                'highlight_color': '#e91e63',
                'is_featured': False,
            },
            'ai_chatbot': {
                'detailed_description': 'AI-powered chatbot that acts as your virtual CEO. Get instant answers to business questions, receive recommendations, and access insights 24/7.',
                'features': [
                    'Natural language business queries',
                    'Instant answers to questions',
                    'Business recommendations',
                    'Data analysis on demand',
                    'Report generation via chat',
                    'Multi-language support',
                    'Learning from your business data',
                    'Voice and text interaction',
                ],
                'benefits': [
                    'Get instant business insights',
                    'Make decisions faster',
                    'Learn business best practices',
                    'Access expertise anytime',
                    'Improve operational efficiency',
                ],
                'use_cases': [
                    'Ask "What are my best-selling products?"',
                    'Get recommendations for promotions',
                    'Analyze sales trends on demand',
                    'Receive business advice',
                ],
                'target_business_types': ['all'],
                'icon': '💬',
                'highlight_color': '#16a085',
                'is_featured': True,
            },
            'weekly_reports': {
                'detailed_description': 'Automated weekly business reports delivered to your email. Stay informed without logging in. Get summaries, trends, and alerts automatically.',
                'features': [
                    'Automated email reports',
                    'Customizable report content',
                    'Weekly summary of key metrics',
                    'Trend analysis',
                    'Comparison with previous periods',
                    'PDF and Excel formats',
                    'Scheduled delivery',
                    'Multi-recipient support',
                ],
                'benefits': [
                    'Stay informed without daily logins',
                    'Share reports with stakeholders easily',
                    'Track progress over time',
                    'Identify trends automatically',
                    'Save time on report generation',
                ],
                'use_cases': [
                    'Receive weekly sales summary',
                    'Share reports with partners',
                    'Track monthly progress',
                    'Monitor key performance indicators',
                ],
                'target_business_types': ['all'],
                'icon': '📧',
                'highlight_color': '#95a5a6',
                'is_featured': False,
            },
            'credit_scoring': {
                'detailed_description': 'Assess customer creditworthiness automatically. Make informed decisions on credit sales, manage risk, and protect your business.',
                'features': [
                    'Automated credit scoring',
                    'Customer payment history analysis',
                    'Risk assessment',
                    'Credit limit recommendations',
                    'Payment behavior tracking',
                    'Credit alerts',
                    'Credit report generation',
                    'Collection management',
                ],
                'benefits': [
                    'Reduce bad debt by 50%',
                    'Make informed credit decisions',
                    'Protect business from defaults',
                    'Identify reliable customers',
                    'Improve cash flow',
                ],
                'use_cases': [
                    'Assess new customer credit applications',
                    'Set credit limits automatically',
                    'Monitor customer payment behavior',
                    'Identify at-risk accounts',
                ],
                'target_business_types': ['wholesale', 'electronics', 'furniture'],
                'icon': '💰',
                'highlight_color': '#f39c12',
                'is_featured': False,
            },
            'delivery_management': {
                'detailed_description': 'Manage deliveries efficiently. Track orders, assign drivers, optimize routes, and keep customers informed with real-time updates.',
                'features': [
                    'Delivery order management',
                    'Driver assignment and tracking',
                    'Route optimization',
                    'Real-time delivery status',
                    'Customer notifications (SMS/Email)',
                    'Delivery proof capture',
                    'Delivery analytics',
                    'Integration with delivery partners',
                ],
                'benefits': [
                    'Improve delivery efficiency by 30%',
                    'Reduce delivery costs',
                    'Keep customers informed',
                    'Track driver performance',
                    'Optimize delivery routes',
                ],
                'use_cases': [
                    'Track online order deliveries',
                    'Assign deliveries to drivers',
                    'Notify customers of delivery status',
                    'Optimize delivery routes',
                ],
                'target_business_types': ['restaurant', 'ecommerce', 'furniture', 'electronics'],
                'icon': '🚚',
                'highlight_color': '#e67e22',
                'is_featured': False,
            },
            'gift_cards': {
                'detailed_description': 'Boost sales and customer loyalty with gift cards and eWallet. Sell gift cards, manage balances, and offer digital wallet services.',
                'features': [
                    'Physical and digital gift cards',
                    'eWallet for customer accounts',
                    'Gift card sales and activation',
                    'Balance management',
                    'Transaction history',
                    'Expiry date management',
                    'Bulk gift card generation',
                    'Customer self-service portal',
                ],
                'benefits': [
                    'Increase sales with gift cards',
                    'Improve cash flow with pre-payments',
                    'Enhance customer loyalty',
                    'Offer flexible payment options',
                    'Reduce cash handling',
                ],
                'use_cases': [
                    'Sell gift cards for holidays',
                    'Offer eWallet for regular customers',
                    'Provide store credit as refunds',
                    'Create promotional gift cards',
                ],
                'target_business_types': ['clothing', 'cosmetics', 'restaurant', 'electronics', 'general_retail'],
                'icon': '🎁',
                'highlight_color': '#e91e63',
                'is_featured': False,
            },
            'ai_chatbot': {
                'detailed_description': 'AI-powered chatbot that acts as your virtual CEO. Get instant answers to business questions, receive recommendations, and access insights 24/7. Natural language queries, data analysis on demand, and report generation via chat.',
                'features': [
                    'Natural language business queries',
                    'Instant answers to questions',
                    'Business recommendations',
                    'Data analysis on demand',
                    'Report generation via chat',
                    'Multi-language support',
                    'Learning from your business data',
                    'Voice and text interaction',
                    'Conversation history',
                    'Context-aware responses',
                    'Business metrics integration',
                ],
                'benefits': [
                    'Get instant business insights',
                    'Make decisions faster',
                    'Learn business best practices',
                    'Access expertise anytime',
                    'Improve operational efficiency',
                    'Get 24/7 business support',
                    'Understand your data better',
                ],
                'use_cases': [
                    'Ask "What are my best-selling products?"',
                    'Get recommendations for promotions',
                    'Analyze sales trends on demand',
                    'Receive business advice',
                    'Generate reports through conversation',
                    'Get insights on inventory levels',
                    'Understand customer behavior',
                ],
                'target_business_types': ['all'],
                'icon': '🤖',
                'highlight_color': '#16a085',
                'is_featured': True,
            },
        }
        
        updated_count = 0
        for code, enhancements in module_enhancements.items():
            try:
                module = Module.objects.get(code=code)
                for key, value in enhancements.items():
                    setattr(module, key, value)
                module.save()
                updated_count += 1
                self.stdout.write(self.style.SUCCESS(f'Enhanced: {module.name}'))
            except Module.DoesNotExist:
                self.stdout.write(self.style.WARNING(f'Module {code} not found, skipping...'))
        
        self.stdout.write(self.style.SUCCESS(f'\nSuccessfully enhanced {updated_count} modules!'))



