# Generated by Django 4.2.7 on 2025-12-06 13:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_add_advanced_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_base', models.BooleanField(default=False, help_text='Base currency for tenant')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenantCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('rounding_rule', models.CharField(choices=[('none', 'No Rounding'), ('round', 'Round to Nearest'), ('ceil', 'Round Up'), ('floor', 'Round Down')], default='round', max_length=20)),
                ('rounding_to', models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Round to nearest (e.g., 0.01 for cents, 0.10 for dimes)', max_digits=5)),
                ('allow_auto_convert', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='core.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_currencies', to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_currencies',
                'unique_together': {('tenant', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, help_text='1 from_currency = rate to_currency', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('effective_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False, help_text='Lock rate to prevent changes')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exchange_rates', to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_from', to='core.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.tenant')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_to', to='core.currency')),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['-effective_date', '-created_at'],
                'unique_together': {('tenant', 'from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
