# Generated by Django 4.2.7 on 2025-12-06 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0004_add_promotion_models'),
        ('core', '0003_add_till_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Receipt', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('header_text', models.TextField(blank=True, help_text='Custom header text')),
                ('show_logo', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='receipts/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('show_company_name', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=False)),
                ('show_vat_number', models.BooleanField(default=True)),
                ('show_item_description', models.BooleanField(default=True)),
                ('show_item_sku', models.BooleanField(default=False)),
                ('show_item_barcode', models.BooleanField(default=False)),
                ('show_item_tax', models.BooleanField(default=True)),
                ('show_item_discount', models.BooleanField(default=True)),
                ('footer_text', models.TextField(blank=True, default='Thank you for your business!\nNo refunds after 7 days.', help_text='Custom footer message')),
                ('show_qr_code', models.BooleanField(default=True, help_text='Show QR code for verification')),
                ('qr_code_data', models.CharField(blank=True, help_text='QR code data template. Use {invoice_number}, {date}, {amount} placeholders', max_length=500)),
                ('show_zimra_info', models.BooleanField(default=True)),
                ('fiscal_number_label', models.CharField(blank=True, default='Fiscal Invoice No:', max_length=50)),
                ('device_code_label', models.CharField(blank=True, default='Device Code:', max_length=50)),
                ('receipt_width', models.IntegerField(default=80, help_text='Receipt width in mm')),
                ('font_size', models.IntegerField(default=12, help_text='Base font size in pt')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_templates', to='core.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_templates', to='core.tenant')),
            ],
            options={
                'db_table': 'receipt_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_type', models.CharField(choices=[('original', 'Original'), ('duplicate', 'Duplicate'), ('reprint', 'Reprint')], default='original', max_length=20)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printed_receipts', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='pos.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_prints', to='core.tenant')),
            ],
            options={
                'db_table': 'receipt_print_logs',
                'ordering': ['-printed_at'],
            },
        ),
    ]
