# Generated by Django 4.2.7 on 2025-12-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_receipt_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Category identifier code', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this business category')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('requires_expiry_tracking', models.BooleanField(default=False)),
                ('requires_serial_tracking', models.BooleanField(default=False)),
                ('requires_weight_scale', models.BooleanField(default=False)),
                ('requires_variants', models.BooleanField(default=False)),
                ('requires_warranty', models.BooleanField(default=False)),
                ('requires_appointments', models.BooleanField(default=False)),
                ('requires_recipe_costing', models.BooleanField(default=False)),
                ('requires_layby', models.BooleanField(default=False)),
                ('requires_delivery', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Categories',
                'db_table': 'business_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_category_name',
            field=models.CharField(blank=True, help_text="Custom category name if 'Other' is selected", max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_category',
            field=models.ForeignKey(blank=True, help_text='Industry/business category for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.businesscategory'),
        ),
        migrations.CreateModel(
            name='CategoryModuleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this module is required for this category')),
                ('priority', models.IntegerField(default=0, help_text='Priority order for activation (higher = more important)')),
                ('notes', models.TextField(blank=True, help_text='Notes about why this module is recommended')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_mappings', to='core.businesscategory')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='core.module')),
            ],
            options={
                'db_table': 'category_module_mappings',
                'ordering': ['-priority', 'module__name'],
                'unique_together': {('category', 'module')},
            },
        ),
    ]
