# Generated by Django 4.2.7 on 2025-12-07 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_add_business_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental'), ('database_only', 'Database Only'), ('files_only', 'Files Only')], default='full', max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('currency', 'Currency & Exchange Rates'), ('payment', 'Payment Methods'), ('tax', 'Tax & Compliance'), ('pos', 'POS Settings'), ('integration', 'Integrations'), ('security', 'Security'), ('notification', 'Notifications'), ('other', 'Other')], default='other', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='If True, tenants can view this setting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('api_uptime', 'API Uptime'), ('server_load', 'Server Load'), ('database_connections', 'Database Connections'), ('active_pos_terminals', 'Active POS Terminals'), ('sync_errors', 'Sync Errors'), ('active_tenants', 'Active Tenants'), ('total_transactions', 'Total Transactions'), ('response_time', 'Response Time'), ('error_rate', 'Error Rate'), ('storage_usage', 'Storage Usage')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_health_metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['-recorded_at', 'metric_type'], name='system_heal_recorde_a5a43f_idx'), models.Index(fields=['metric_type', '-recorded_at'], name='system_heal_metric__604225_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('update', 'Update'), ('important', 'Important')], default='info', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_tenants', models.ManyToManyField(blank=True, help_text='Leave empty to send to all tenants', to='core.tenant')),
            ],
            options={
                'db_table': 'system_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('tenant_create', 'Tenant Created'), ('tenant_update', 'Tenant Updated'), ('tenant_delete', 'Tenant Deleted'), ('tenant_suspend', 'Tenant Suspended'), ('tenant_activate', 'Tenant Activated'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_suspend', 'User Suspended'), ('setting_change', 'Setting Changed'), ('subscription_change', 'Subscription Changed'), ('login', 'Login'), ('logout', 'Logout'), ('data_export', 'Data Exported'), ('data_import', 'Data Imported'), ('backup_created', 'Backup Created'), ('system_update', 'System Updated'), ('security_alert', 'Security Alert'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_audit_logs', to='core.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='owner_audit_created_185bfd_idx'), models.Index(fields=['action_type'], name='owner_audit_action__09335b_idx'), models.Index(fields=['user', '-created_at'], name='owner_audit_user_id_54103e_idx'), models.Index(fields=['tenant', '-created_at'], name='owner_audit_tenant__5c6cce_idx')],
            },
        ),
    ]
