# Generated by Django 4.2.7 on 2025-12-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_owner_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-is_main', 'name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='branch',
            name='allow_online_orders',
            field=models.BooleanField(default=False, help_text='Allow online orders for this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(default='Zimbabwe', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, help_text='Branch description or notes'),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for mapping', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for mapping', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Opening hours in JSON format: {'monday': {'open': '09:00', 'close': '17:00'}, ...}"),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_alt',
            field=models.CharField(blank=True, help_text='Alternative phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
