# Generated by Django 4.2.7 on 2025-12-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_branch_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workflow_type', models.CharField(choices=[('product_creation', 'Product Creation'), ('sale_processing', 'Sale Processing'), ('inventory_management', 'Inventory Management'), ('reporting', 'Reporting'), ('custom', 'Custom Workflow')], max_length=50)),
                ('config', models.TextField(default='{}', help_text='Workflow configuration in JSON format')),
                ('rules', models.TextField(blank=True, default='[]', help_text="Business rules as JSON: [{'condition': '...', 'action': '...'}]")),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.businesscategory')),
            ],
            options={
                'db_table': 'category_workflows',
                'ordering': ['category', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('profit', 'Profit & Loss'), ('custom', 'Custom Report')], max_length=50)),
                ('config', models.TextField(default='{}', help_text='Report configuration as JSON: columns, filters, charts, etc.')),
                ('default_filters', models.TextField(blank=True, default='{}')),
                ('chart_config', models.TextField(blank=True, default='{}')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='core.businesscategory')),
            ],
            options={
                'db_table': 'category_report_templates',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Internal field identifier', max_length=100)),
                ('field_label', models.CharField(help_text='Display label', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('select', 'Select/Dropdown'), ('multiselect', 'Multi-Select'), ('textarea', 'Textarea'), ('file', 'File Upload'), ('json', 'JSON/Object')], default='text', max_length=20)),
                ('is_visible', models.BooleanField(default=True, help_text='Show this field in forms')),
                ('is_required', models.BooleanField(default=False, help_text='Field is required')),
                ('is_searchable', models.BooleanField(default=False, help_text='Include in search')),
                ('default_value', models.TextField(blank=True, help_text='Default value (JSON encoded if complex)')),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True, help_text='Help text to display')),
                ('options', models.TextField(blank=True, default='{}', help_text="Options for select/multiselect as JSON: {'choices': [{'value': 'x', 'label': 'X'}]}")),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, help_text='Regex pattern for validation', max_length=255)),
                ('section', models.CharField(default='general', help_text='Form section/tab', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('width', models.CharField(default='full', help_text='Field width: full, half, third, quarter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='core.businesscategory')),
            ],
            options={
                'db_table': 'category_field_definitions',
                'ordering': ['section', 'sort_order', 'field_label'],
                'unique_together': {('category', 'field_key')},
            },
        ),
    ]
