# Generated by Django 4.2.7 on 2025-12-07 11:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_industry_specific_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this pricing rule', max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Code identifier for this rule', unique=True)),
                ('category_price_monthly', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Price per business category per month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user_price_monthly', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Price per user per month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('branch_price_monthly', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Price per extra branch per month (beyond first branch)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('yearly_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percentage discount for yearly payments (e.g., 20.00 for 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', help_text='Default currency for pricing', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pricing rule is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Default pricing rule to use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_rules',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModulePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price override for this module', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price override (if not set, calculated with discount)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_overrides', to='core.module')),
                ('pricing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_pricing', to='core.pricingrule')),
            ],
            options={
                'db_table': 'module_pricing',
                'unique_together': {('pricing_rule', 'module')},
            },
        ),
    ]
