# Generated by Django 4.2.7 on 2025-12-10 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_pricing_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='approved_by_signature',
            field=models.ImageField(blank=True, help_text='Approver signature for documents requiring approval', null=True, upload_to='tenant_signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo used across the system (receipts, reports, etc.)', null=True, upload_to='tenant_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gif'])]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='manager_signature',
            field=models.ImageField(blank=True, help_text='Manager signature for documents and reports', null=True, upload_to='tenant_signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='prepared_by_signature',
            field=models.ImageField(blank=True, help_text='Prepared by signature for documents', null=True, upload_to='tenant_signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
