# Generated by Django 4.2.7 on 2025-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_tenant_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP code or postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state_province',
            field=models.CharField(blank=True, help_text='State, province, or region', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, help_text='Street address'),
        ),
    ]
