# Generated by Django 4.2.7 on 2025-12-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='state_province',
            field=models.CharField(blank=True, help_text='State, province, or region', max_length=100),
        ),
    ]
