# Generated by Django 4.2.7 on 2025-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_branch_address_line_2_branch_state_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('telecash', 'Telecash'), ('zipit', 'ZIPIT'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], help_text='Preferred payment method for subscriptions', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Preferred subscription billing cycle', max_length=20),
        ),
    ]
