# Generated by Django 4.2.7 on 2025-12-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_subscription_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text="List of benefits: ['Benefit 1', 'Benefit 2']"),
        ),
        migrations.AddField(
            model_name='module',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed description with benefits and use cases'),
        ),
        migrations.AddField(
            model_name='module',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='URL to detailed documentation'),
        ),
        migrations.AddField(
            model_name='module',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="List of key features: ['Feature 1', 'Feature 2']"),
        ),
        migrations.AddField(
            model_name='module',
            name='highlight_color',
            field=models.CharField(blank=True, help_text='Hex color for module card (e.g., #667eea)', max_length=7),
        ),
        migrations.AddField(
            model_name='module',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this module prominently in package displays'),
        ),
        migrations.AddField(
            model_name='module',
            name='target_business_types',
            field=models.JSONField(blank=True, default=list, help_text='Business types this module is ideal for'),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='use_cases',
            field=models.JSONField(blank=True, default=list, help_text="List of use cases: ['Use case 1', 'Use case 2']"),
        ),
        migrations.AddField(
            model_name='module',
            name='video_demo_url',
            field=models.URLField(blank=True, help_text='URL to video demonstration'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or name (emoji)', max_length=50),
        ),
    ]
